services:
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: pnpm run start:dev users
    env_file:
      - ./apps/users/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      target: development
    command: pnpm run start:dev admin
    env_file:
      - ./apps/admin/.env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
  
